create time app
Anna1327/time_app pull request #1
Opened 2023-11-17 20:21 UTC by Anna1327

2023-11-18 19:19 UTC, BubuntuClu requested changes

2023-11-18 19:19 UTC, BubuntuClu commented on date_time_format.rb
> +    @params.all? { |param| @available_params.include?(param) }
у тебя тут перебор параметров происходит. потом в каждом из методов для ответа происходит перебор параметров. в ответе времени ты даже дважды это делаешь. это очень не оптимально

выдели метод `call` который за раз обойдет все параметры и соберет нужные тебе массивы верных/неверных параметров. их уже используй в последующих методах

2023-11-18 19:19 UTC, BubuntuClu commented on app.rb
> +    request_failure || time_request
смущает меня такая констуркция кода. как только ты забудешь что метод `request_failure` должен вернуть `nil` или что-то пустое, что руби посчитает как `nil`, то ты сразу сломаешь свою программу.

выдели метод обработчик запроса, если он проваливается то отправляй ошибку, если нет, то уходи в обработку запроса

```
if request_invalid?
  response_failure
else
  handle_request
end
```
как-то так, мне кажется, так будет безопаснее

2023-11-18 19:19 UTC, BubuntuClu commented on app.rb
> +    return response(400, "Unknown time format #{datetime.wrong_params}") unless datetime.valid?
```
datetime = DateTimeFormat.new(time_now_format)
datetime.call
if datetime.valid?
  response success
else
 response invalid
end
```

добавь гибкости в программу

2023-11-18 19:19 UTC, BubuntuClu commented on date_time_format.rb
> +  DATE_FORMATS = {
точно ли нужно делать два разных хэша? в ТЗ не сказано про формат отдачи. делая разделение на дату и время(формат вывода через разные разделители) ты себе усложняешь задачу. в космоес не летим на этом коде, усложнять как будто бы не зачем

2023-11-19 01:17 UTC, Anna1327 commented on date_time_format.rb
> +  DATE_FORMATS = {
оставила '-'

2023-11-19 17:22 UTC, BubuntuClu requested changes

2023-11-19 17:22 UTC, BubuntuClu commented on date_time_format.rb
> +      @valid << find_valid_params(param)
```
if VALID_FORMATS[param]
  @valid << VALID_FORMATS[param]
else
  @wrong_params << param
end
```
у тебя как-то сложно получилось

2023-11-19 17:22 UTC, BubuntuClu commented on date_time_format.rb
> +    datetime_string = @params.map { |param| VALID_FORMATS[param] }.compact.join('-')
и зачем тогда собирали масив @valid если его не используем? ты все так же по параметрам делаешь обход. `Time.now.strftime(@valid.join('-'))` примерно так будет

2023-11-19 17:22 UTC, BubuntuClu commented on date_time_format.rb
> +    @params == @valid
лучше проверить что массив ошибок пустой

2023-11-19 17:22 UTC, BubuntuClu commented on date_time_format.rb
> +    @wrong_params.compact!.to_s
не совсем понял задумку этого кода. объясни, пжлст

2023-11-19 17:22 UTC, BubuntuClu commented on date_time_format.rb
>    end
эти методы не нужны, их можно удалить

2023-11-19 18:40 UTC, Anna1327 commented on date_time_format.rb
> +    @wrong_params.compact!.to_s
да я что-то перемудрила, не подумала, что никаких nil в массиве уже быть не может

2023-11-20 09:49 UTC, merged